### ISSUE TITLE
Docker with duktape is broken

### ISSUE THREAD

**Issue by lwizchz** [googleprojectzero/fuzzilli#193]
Hi I've been trying to get the duktape Dockerfile to work but haven't been able to so far.
<details>
<summary>The output if I run `sudo ./build.sh duktape`:</summary>

```
[*] Building Fuzzilli
Sending build context to Docker daemon  32.91MB
Step 1/8 : FROM swift:latest
 ---> a96910764a17
Step 2/8 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 1ce63ea31806
Step 3/8 : ENV SHELL=bash
 ---> Using cache
 ---> 3dbbb0ef5f6f
Step 4/8 : RUN apt-get -y update && apt-get -y upgrade
 ---> Using cache
 ---> 328b5f40d6db
Step 5/8 : RUN useradd -m builder
 ---> Using cache
 ---> 4d2f9b60a91d
Step 6/8 : WORKDIR /home/builder
 ---> Using cache
 ---> 6044904a9ed2
Step 7/8 : ADD fuzzilli fuzzilli
 ---> Using cache
 ---> c10c59937099
Step 8/8 : RUN cd fuzzilli && swift test && swift build -c release
 ---> Using cache
 ---> 1cf2b18b9bc6
Successfully built 1cf2b18b9bc6
Successfully tagged fuzzilli_builder:latest
341aa60ffd1099c653cf335ae0599054aa1ff68ed5b849ea375a90c4a1efe8b4
temp_container
[*] Building Duktape
Sending build context to Docker daemon  5.632kB
Step 1/13 : FROM swift:latest
 ---> a96910764a17
Step 2/13 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 1ce63ea31806
Step 3/13 : ENV SHELL=bash
 ---> Using cache
 ---> 3dbbb0ef5f6f
Step 4/13 : RUN apt-get -y update && apt-get -y upgrade
 ---> Using cache
 ---> 328b5f40d6db
Step 5/13 : RUN apt-get install -y git make clang bc python-pip
 ---> Using cache
 ---> 4803f52e3514
Step 6/13 : RUN pip install pyyaml
 ---> Using cache
 ---> 1f0bef87c1cc
Step 7/13 : RUN useradd -m builder
 ---> Using cache
 ---> e0edfa90367c
Step 8/13 : RUN git clone https://github.com/svaarala/duktape.git /home/builder/duktape
 ---> Using cache
 ---> 5e9e1314f3c3
Step 9/13 : WORKDIR /home/builder/duktape
 ---> Using cache
 ---> 0219b6cd81e6
Step 10/13 : ARG rev
 ---> Using cache
 ---> 7201b0bf4f10
Step 11/13 : RUN git pull && git checkout $rev
 ---> Using cache
 ---> 70eda74ac796
Step 12/13 : RUN apt-get -y update && apt-get -y upgrade
 ---> Using cache
 ---> 9d8001fffd22
Step 13/13 : RUN make build/duk-fuzzilli
 ---> Running in 7dcad6a0accb
/usr/bin/git clone -q --depth 1 -b fix-compile-warnings-duktape https://github.com/svaarala/linenoise.git deps/linenoise
touch deps/linenoise
/usr/bin/python2 tools/configure.py --output-directory ./prep/fuzz --source-directory src-input --config-metadata config --option-file util/makeduk_base.yaml --option-file util/makeduk_fuzz.yaml --line-directives

****************************************************************************                        
*** Duktape python tooling is obsolete, migrate to JS-based tooling!     ***                        
*** This tool now internally invokes the JS-based tooling.               ***                        
*** Minimum Node.js version is 14.x.                                     ***                        
****************************************************************************                        
                                                                                                    
Traceback (most recent call last):                                                                  
  File "tools/configure.py", line 222, in <module>                                                  
    main()                                                                                          
  File "tools/configure.py", line 155, in main                                                      
    raise Exception('failed to detect Node.js, override with --nodejs-command')                     
Exception: failed to detect Node.js, override with --nodejs-command                                 
Makefile:331: recipe for target 'prep/fuzz' failed                                                  
make: *** [prep/fuzz] Error 1
The command '/bin/sh -c make build/duk-fuzzilli' returned a non-zero code: 2
```

</details>

So it seems the error is due to duktape switching to nodejs. I've patched together a Dockerfile that gets partway but still no luck.

<details>
<summary>Cloud/Docker/DuktapeBuilder/Dockerfile</summary>

```dockerfile
FROM swift:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL=bash

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install -y git make clang bc python-pip nodejs npm

# Dependency of the duktape build process
RUN pip install pyyaml

RUN useradd -m builder

RUN git clone https://github.com/svaarala/duktape.git /home/builder/duktape
WORKDIR /home/builder/duktape

# The hash of the most recent commit is passed in from the build script, to ensure proper caching behavior
ARG rev
RUN git pull && git checkout $rev

# Update system packages first
RUN apt-get -y update && apt-get -y upgrade

# NodeJs Dependencies
RUN npm i -g js-yaml
RUN mkdir /home/builder/duktape/src-tools/lib/extdeps
RUN ln -s /usr/local/lib/node_modules/js-yaml/bin/js-yaml.js /home/builder/duktape/src-tools/lib/extdeps/js-yaml.js

# Patch files
RUN sed -i 's/catch {}/catch (e) {}/g' /usr/local/lib/node_modules/js-yaml/node_modules/argparse/argparse.js

# Assume that the current master branch maintains duk-fuzzilli
# No need to patch, as the fuzz target is maintained in the duktape repo
# Start building!
RUN make build/duk-fuzzilli
```

</details>

<details>
<summary>For some reason it seems to be passing the program args to js-yaml, here's the new error:</summary>

```
[*] Building Fuzzilli
Sending build context to Docker daemon  32.91MB
Step 1/8 : FROM swift:latest
 ---> a96910764a17
Step 2/8 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 1ce63ea31806
Step 3/8 : ENV SHELL=bash
 ---> Using cache
 ---> 3dbbb0ef5f6f
Step 4/8 : RUN apt-get -y update && apt-get -y upgrade
 ---> Using cache
 ---> 328b5f40d6db
Step 5/8 : RUN useradd -m builder
 ---> Using cache
 ---> 4d2f9b60a91d
Step 6/8 : WORKDIR /home/builder
 ---> Using cache
 ---> 6044904a9ed2
Step 7/8 : ADD fuzzilli fuzzilli
 ---> Using cache
 ---> c10c59937099
Step 8/8 : RUN cd fuzzilli && swift test && swift build -c release
 ---> Using cache
 ---> 1cf2b18b9bc6
Successfully built 1cf2b18b9bc6
Successfully tagged fuzzilli_builder:latest
15aeb927fc1b075aa13d529263f0229cff8d0632fc6f325315a5f42d0648f69f
temp_container
[*] Building Duktape
Sending build context to Docker daemon  6.144kB
Step 1/17 : FROM swift:latest
 ---> a96910764a17
Step 2/17 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 1ce63ea31806
Step 3/17 : ENV SHELL=bash
 ---> Using cache
 ---> 3dbbb0ef5f6f
Step 4/17 : RUN apt-get -y update && apt-get -y upgrade
 ---> Using cache
 ---> 328b5f40d6db
Step 5/17 : RUN apt-get install -y git make clang bc python-pip nodejs npm
 ---> Using cache
 ---> 00db9ad255dd
Step 6/17 : RUN pip install pyyaml
 ---> Using cache
 ---> a708de98e2f2
Step 7/17 : RUN useradd -m builder
 ---> Using cache
 ---> 89fadfaca331
Step 8/17 : RUN git clone https://github.com/svaarala/duktape.git /home/builder/duktape
 ---> Using cache
 ---> 03da354eafcf
Step 9/17 : WORKDIR /home/builder/duktape
 ---> Using cache
 ---> b12be1c4aead
Step 10/17 : ARG rev
 ---> Using cache
 ---> bb74c640c683
Step 11/17 : RUN git pull && git checkout $rev
 ---> Using cache
 ---> 75112d65d33d
Step 12/17 : RUN apt-get -y update && apt-get -y upgrade
 ---> Using cache
 ---> a916302e252d
Step 13/17 : RUN npm i -g js-yaml
 ---> Using cache
 ---> 1e79417d4939
Step 14/17 : RUN mkdir /home/builder/duktape/src-tools/lib/extdeps
 ---> Using cache
 ---> 5baf8868ed24
Step 15/17 : RUN ln -s /usr/local/lib/node_modules/js-yaml/bin/js-yaml.js /home/builder/duktape/src-tools/lib/extdeps/js-yaml.js
 ---> Using cache
 ---> 8344e9d3c8ac
Step 16/17 : RUN sed -i 's/catch {}/catch (e) {}/g' /usr/local/lib/node_modules/js-yaml/node_modules/argparse/argparse.js
 ---> Using cache
 ---> d0804ec41c14
Step 17/17 : RUN make build/duk-fuzzilli
 ---> Running in 18c732515062
/usr/bin/git clone -q --depth 1 -b fix-compile-warnings-duktape https://github.com/svaarala/linenoise.git deps/linenoise
touch deps/linenoise
/usr/bin/python2 tools/configure.py --output-directory ./prep/fuzz --source-directory src-input --config-metadata config --option-file util/makeduk_base.yaml --option-file util/makeduk_fuzz.yaml --line-directives

****************************************************************************                                                                                
*** Duktape python tooling is obsolete, migrate to JS-based tooling!     ***                        
*** This tool now internally invokes the JS-based tooling.               ***                        
*** Minimum Node.js version is 14.x.                                     ***                        
****************************************************************************                        
                                                                                                    
*** Executing JS-based tooling with command: ['nodejs', '/home/builder/duktape/tools/../src-tools/index.js', 'configure', '--output-directory', './prep/fuzz', '--source-directory', 'src-input', '--config-directory', 'config', '--option-file', '/tmp/tmp5bcu0g', '--fixup-file', '/tmp/tmpNs61Fr', '--line-directives']                                                                                     
                                                                                                    
usage: js-yaml [-h] [-v] [-c] [-t] [file]                                                           
js-yaml: error: unrecognized arguments: --output-directory ./prep/fuzz --source-directory src-input --config-directory config --option-file /tmp/tmp5bcu0g --fixup-file /tmp/tmpNs61Fr --line-directives
Traceback (most recent call last):                                                                  
  File "tools/configure.py", line 222, in <module>                                                  
    main()                                                                                          
  File "tools/configure.py", line 219, in main                                                      
    subprocess.check_call(cmd)                                                                      
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call                                  
    raise CalledProcessError(retcode, cmd)                                                          
subprocess.CalledProcessError: Command '['nodejs', '/home/builder/duktape/tools/../src-tools/index.js', 'configure', '--output-directory', './prep/fuzz', '--source-directory', 'src-input', '--config-directory', 'config', '--option-file', '/tmp/tmp5bcu0g', '--fixup-file', '/tmp/tmpNs61Fr', '--line-directives']' returned non-zero exit status 2                                                         
make: *** [prep/fuzz] Error 1                                                                       
Makefile:331: recipe for target 'prep/fuzz' failed                                                  
The command '/bin/sh -c make build/duk-fuzzilli' returned a non-zero code: 2
```

</details>

Any help would be greatly appreciated!

**Comment by lwizchz** [comment]
I figured out that since duktape moved to node, the default make target needs to be run to properly pull down those dependencies. Here's the working `DuktapeBuilder/Dockerfile`:

```dockerfile
FROM swift:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL=bash

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install -y git make clang bc curl python-pip nodejs npm

# Update NodeJS and NPM to the latest versions
RUN npm install -g n
RUN n latest
RUN npm install -g npm

# Dependency of the duktape build process
RUN pip install pyyaml

RUN useradd -m builder

RUN git clone https://github.com/svaarala/duktape.git /home/builder/duktape
WORKDIR /home/builder/duktape

# The hash of the most recent commit is passed in from the build script, to ensure proper caching behavior
ARG rev
RUN git pull && git checkout $rev

# Update system packages first
RUN apt-get -y update && apt-get -y upgrade

# Make normally to pull down NodeJS deps
RUN make

# Assume that the current master branch maintains duk-fuzzilli
# No need to patch, as the fuzz target is maintained in the duktape repo
# Start building!
RUN make build/duk-fuzzilli
```

I also had to add `--network host` to each `docker build` command in the `build.sh` scripts but I'm not sure whether that's necessary.

**Comment by saelo** [comment]
Great! Feel free to open a PR to get those fixes merged :)
I don't think `--network host` should be necessary as the default (`--network bridge`) should be enough for the containers to fetch stuff from the internet etc (without exposing host network interfaces to the container). But better double check.

**Comment by lwizchz** [comment]
If the network works for you then I won't add it but I was getting DNS resolution errors which is why I needed it

**Comment by saelo** [comment]
Fixed with https://github.com/googleprojectzero/fuzzilli/pull/194
