### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by fr3ns1s** [googleprojectzero/fuzzilli#307]
what am I doing wrong here ?

macbook m1 12.0.1 

Webkit head is on d15731adac91
MD5 (Source/JavaScriptCore/jsc.cpp) after patch = cfe2b60293a8c319fa5222b16bac8175

```
➜  fuzzilli git:(main) ✗ swift run -c release FuzzilliCli --profile=jsc --storagePath=Crash --overwrite --jobs=48 /Users/fp/Documents/Git/WebKitFuzzilli/FuzzBuild/Debug/bin/jsc 
[0/0] Build complete!
[Cli] Deleting all files in Crash due to --overwrite
[REPRL] Script execution failed: Did not receive HELO message from child: No such file or directory. Retrying in 1 second...
[REPRL] Script execution failed again: Did not receive HELO message from child: Operation timed out. Giving up
[Coverage] Initialized, 924657 edges
[JavaScriptEnvironment] initialized static JS environment model
[JavaScriptEnvironment] Have 60 available builtins: ["undefined", "RegExp", "WeakMap", "Number", "isFinite", "TypeError", "BigInt", "fullGC", "Reflect", "EvalError", "RangeError", "SyntaxError", "Int16Array", "Object", "createGlobalObject", "Function", "Error", "Array", "String", "Uint16Array", "WeakSet", "AggregateError", "NaN", "OSRExit", "forceGCSlowPaths", "Infinity", "Uint32Array", "drainMicrotasks", "Uint8Array", "Uint8ClampedArray", "makeMasquerader", "JSON", "Map", "noInline", "runString", "Int32Array", "noFTL", "isNaN", "Int8Array", "transferArrayBuffer", "Boolean", "Float32Array", "Symbol", "Set", "parseInt", "Date", "ArrayBuffer", "Float64Array", "parseFloat", "placeholder", "Math", "fiatInt52", "edenGC", "Promise", "eval", "Proxy", "DataView", "gc", "ReferenceError", "ensureArrayStorage"]
[JavaScriptEnvironment] Have 211 available method names: ["getMonth", "toTimeString", "fromCodePoint", "getUTCSeconds", "log", "isExtensible", "clz32", "padStart", "clear", "setPrototypeOf", "keys", "search", "flat", "match", "isFrozen", "isArray", "hypot", "setSeconds", "trimStart", "getYear", "replace", "set", "defineProperty", "reject", "sign", "toLowerCase", "race", "setHours", "m", "tanh", "sinh", "getTime", "getMinutes", "getUTCFullYear", "isFinite", "is", "toString", "some", "setUint32", "copyWithin", "for", "defineProperties", "map", "cosh", "replaceAll", "values", "getUTCMonth", "asIntN", "trimRight", "n", "isSealed", "getSeconds", "seal", "fromCharCode", "toGMTString", "log2", "shift", "getDay", "localeCompare", "endsWith", "asinh", "getInt32", "deleteProperty", "apply", "setYear", "toLocaleString", "split", "expm1", "acosh", "getUTCDay", "construct", "assign", "toDateString", "filter", "catch", "getUint16", "getOwnPropertySymbols", "min", "all", "cos", "get", "matchAll", "getUTCHours", "setUint16", "log1p", "slice", "setFloat64", "toISOString", "toUTCString", "random", "forEach", "indexOf", "allSettled", "getUint8", "freeze", "subarray", "atanh", "setUTCSeconds", "getTimezoneOffset", "keyFor", "bind", "fill", "reverse", "tan", "trimLeft", "round", "atan2", "imul", "push", "fround", "atan", "charAt", "getInt16", "exec", "setUTCMonth", "setMonth", "getUTCMilliseconds", "splice", "setUTCHours", "acos", "sort", "delete", "flatMap", "getPrototypeOf", "parse", "getDate", "trimEnd", "substring", "getOwnPropertyNames", "getInt8", "getUTCMinutes", "getFloat64", "setMilliseconds", "getHours", "now", "UTC", "sqrt", "padEnd", "sin", "getOwnPropertyDescriptor", "abs", "charCodeAt", "getFullYear", "setTime", "find", "getOwnPropertyDescriptors", "preventExtensions", "floor", "getUTCDate", "getMilliseconds", "has", "setMinutes", "setUTCDate", "codePointAt", "setInt8", "resolve", "isNaN", "startsWith", "exp", "setFullYear", "isInteger", "trunc", "reduce", "toJSON", "create", "setUTCFullYear", "isSafeInteger", "add", "includes", "setDate", "unshift", "setUint8", "getUint32", "ceil", "join", "compile", "lastIndexOf", "asin", "log10", "findIndex", "of", "setInt32", "isView", "setUTCMilliseconds", "test", "every", "cbrt", "ownKeys", "then", "finally", "from", "asUintN", "reduceRight", "setUTCMinutes", "pop", "fromEntries", "toUpperCase", "setInt16", "call", "getFloat32", "setFloat32", "repeat", "stringify", "max", "entries", "concat", "o", "trim", "p", "raw", "pow"]
[JavaScriptEnvironment] Have 51 property names that are available for read access: ["byteOffset", "iterator", "replace", "source", "unicode", "constructor", "matchAll", "b", "match", "toStringTag", "arguments", "MIN_SAFE_INTEGER", "dotAll", "MIN_VALUE", "global", "sticky", "message", "unscopable", "caller", "NaN", "name", "isConcatSpreadable", "PI", "toString", "hasInstance", "__proto__", "d", "MAX_VALUE", "prototype", "byteLength", "NEGATIVE_INFINITY", "length", "multiline", "MAX_SAFE_INTEGER", "e", "buffer", "toPrimitive", "species", "E", "POSITIVE_INFINITY", "flags", "asyncIterator", "split", "search", "size", "valueOf", "EPSILON", "ignoreCase", "description", "c", "a"]
[JavaScriptEnvironment] Have 10 property names that are available for write access: ["c", "__proto__", "constructor", "toString", "length", "e", "d", "a", "valueOf", "b"]
[JavaScriptEnvironment] Have 5 custom property names: ["c", "d", "b", "e", "a"]
[JavaScriptEnvironment] Have 4 custom method names: ["m", "n", "o", "p"]
[Fuzzer] Initialized
[REPRL] Script execution failed: Did not receive HELO message from child: Operation timed out. Retrying in 1 second...
[REPRL] Script execution failed again: Did not receive HELO message from child: Operation timed out. Giving up
[Fuzzer] Cannot execute programs (exit code must be zero when no exception was thrown). Are the command line flags valid?
[Fuzzer] Shutting down due to fatal error

++++++++++ Fuzzer Finished ++++++++++

Fuzzer Statistics
-----------------
Total Samples:                0
Interesting Samples Found:    0
Valid Samples Found:          0
Corpus Size:                  0
Correctness Rate:             nan%
Timeout Rate:                 nan%
Crashes Found:                0
Timeouts Hit:                 0
Coverage:                     0.00%
Avg. program size:            0.00
Connected workers:            0
Execs / Second:               0.00
Fuzzer Overhead:              100.00%
Total Execs:                  1
```

this is  the tester's log

```
➜  fuzzilli git:(main) ✗ ./tester /Users/fp/Documents/Git/WebKitFuzzilli/FuzzBuild/Debug/bin/jsc --reprl
[COV] edge counters initialized. Shared memory: shm_id_16411 with 924656 edges
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==16412==ERROR: UndefinedBehaviorSanitizer: BUS on unknown address (pc 0x0001b4bcc1b8 bp 0x000102842908 sp 0x00016d726a70 T14319914)
==16412==The signal is caused by a UNKNOWN memory access.
==16412==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x1b4bcc1b8 in _platform_memmove+0xa8 (libsystem_platform.dylib:arm64e+0x41b8)

==16412==Register values:
 x[0] = 0x000000011f004000   x[1] = 0x0000000107124100   x[2] = 0x000000000000009c   x[3] = 0x000000011f004020  
 x[4] = 0xffffffffe81200c0   x[5] = 0x0000000000000020   x[6] = 0x00000000000000b5   x[7] = 0x0000000000000001  
 x[8] = 0x0000000107000d9a   x[9] = 0x0000000000000032  x[10] = 0x0000000000000030  x[11] = 0x00000000000000c0  
x[12] = 0x00000001028438c4  x[13] = 0x0000000000000044  x[14] = 0x000000703e5027c8  x[15] = 0x0000000000009c38  
x[16] = 0x00000001b4bcc110  x[17] = 0x0000600001510000  x[18] = 0x0000000000000000  x[19] = 0x000000011f004000  
x[20] = 0x0000000105308000  x[21] = 0x00000001071240c0  x[22] = 0x00000001071e4180  x[23] = 0x00000000000000bc  
x[24] = 0x0000000000000040  x[25] = 0x0000000000000040  x[26] = 0x0000000107124100  x[27] = 0x000000016d726d20  
x[28] = 0x000000016d726c38     fp = 0x000000016d726b80     lr = 0x0000000102842908     sp = 0x000000016d726a70  
UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: BUS (libsystem_platform.dylib:arm64e+0x41b8) in _platform_memmove+0xa8
==16412==ABORTING
read(crfd, &helo, 4) failed[1]    16411 abort      ./tester /Users/fp/Documents/Git/WebKitFuzzilli/FuzzBuild/Debug/bin/jsc 
```

**Comment by fr3ns1s** [comment]
works fine on i7

**Comment by saelo** [comment]
Interesting, seems like _something_ is working since it get's here `[COV] edge counters initialized. Shared memory: shm_id_16411 with 924656 edges` which means that the target binary at least finished the sanitizer coverage initialization. Is that crash just because the `read(crfd, &helo, 4)` in `./tester` failed? Can you run `/Users/fp/Documents/Git/WebKitFuzzilli/FuzzBuild/Debug/bin/js` without `--reprl`?

**Comment by fr3ns1s** [comment]
here is it

```
➜  fuzzilli git:(main) ✗ /Users/fp/Documents/Git/WebKitFuzzilli/FuzzBuild/Debug/bin/jsc
[COV] no shared memory bitmap available, skipping
[COV] edge counters initialized. Shared memory: (null) with 924656 edges
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==71909==ERROR: UndefinedBehaviorSanitizer: BUS on unknown address (pc 0x0001b4bcc1b8 bp 0x000100e32898 sp 0x00016f136ac0 T15409046)
==71909==The signal is caused by a UNKNOWN memory access.
==71909==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x1b4bcc1b8 in _platform_memmove+0xa8 (libsystem_platform.dylib:arm64e+0x41b8)

==71909==Register values:
 x[0] = 0x0000000105704000   x[1] = 0x0000000105624100   x[2] = 0x000000000000009c   x[3] = 0x0000000105704020  
 x[4] = 0xfffffffffff200c0   x[5] = 0x0000000000000020   x[6] = 0x00000000000000b5   x[7] = 0x0000000000000001  
 x[8] = 0x0000000138008d9a   x[9] = 0x0000000000000032  x[10] = 0x0000000000000030  x[11] = 0x00000000000000c0  
x[12] = 0x0000000100e33854  x[13] = 0x0000000000000044  x[14] = 0x0000007097f027c8  x[15] = 0x0000000000009c38  
x[16] = 0x00000001b4bcc110  x[17] = 0x0000600001b2c000  x[18] = 0x0000000000000000  x[19] = 0x0000000105704000  
x[20] = 0x00000001038f8000  x[21] = 0x00000001056240c0  x[22] = 0x0000000105628000  x[23] = 0x00000000000000bc  
x[24] = 0x0000000000000040  x[25] = 0x0000000000000040  x[26] = 0x0000000105624100  x[27] = 0x000000016f136d70  
x[28] = 0x000000016f136c88     fp = 0x000000016f136bd0     lr = 0x0000000100e32898     sp = 0x000000016f136ac0  
UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: BUS (libsystem_platform.dylib:arm64e+0x41b8) in _platform_memmove+0xa8
==71909==ABORTING
[1]    71909 abort      /Users/fp/Documents/Git/WebKitFuzzilli/FuzzBuild/Debug/bin/jsc
```

**Comment by fr3ns1s** [comment]
```
Process 72198 launched: '/Users/fp/Documents/Git/WebKitFuzzilli/FuzzBuild/Debug/bin/jsc' (arm64)
[COV] no shared memory bitmap available, skipping
[COV] edge counters initialized. Shared memory: (null) with 924656 edges
Process 72198 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x110004000)
    frame #0: 0x00000001b4bcc1b8 libsystem_platform.dylib`_platform_memmove + 168
libsystem_platform.dylib`_platform_memmove:
->  0x1b4bcc1b8 <+168>: stp    q2, q3, [x0]
    0x1b4bcc1bc <+172>: subs   x2, x2, #0x40             ; =0x40 
    0x1b4bcc1c0 <+176>: b.ls   0x1b4bcc1dc               ; <+204>
    0x1b4bcc1c4 <+180>: stp    q0, q1, [x3]
Target 0: (jsc) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x110004000)
  * frame #0: 0x00000001b4bcc1b8 libsystem_platform.dylib`_platform_memmove + 168
    frame #1: 0x000000010016a898 jsc`void JSC::LinkBuffer::copyCompactAndLinkCode<unsigned int>(this=<unavailable>, macroAssembler=<unavailable>, effort=<unavailable>) at LinkBuffer.cpp:372:9 [opt]
    frame #2: 0x0000000100169538 jsc`JSC::LinkBuffer::linkCode(this=0x000000016fdfebb8, macroAssembler=0x000000016fdfeca0, effort=JITCompilationMustSucceed) at LinkBuffer.cpp:416:5 [opt]
    frame #3: 0x00000001013c3144 jsc`JSC::nativeForGenerator(JSC::VM&, JSC::ThunkFunctionType, JSC::CodeSpecializationKind, JSC::ThunkEntryType) [inlined] JSC::LinkBuffer::LinkBuffer(this=0x000000016fdfebb8, macroAssembler=0x000000016fdfeca0, profile=Thunk, effort=JITCompilationMustSucceed) at LinkBuffer.h:125:9 [opt]
    frame #4: 0x00000001013c30f0 jsc`JSC::nativeForGenerator(JSC::VM&, JSC::ThunkFunctionType, JSC::CodeSpecializationKind, JSC::ThunkEntryType) [inlined] JSC::LinkBuffer::LinkBuffer(this=0x000000016fdfebb8, macroAssembler=0x000000016fdfeca0, profile=Thunk, effort=JITCompilationMustSucceed) at LinkBuffer.h:123:5 [opt]
    frame #5: 0x00000001013c30f0 jsc`JSC::nativeForGenerator(vm=<unavailable>, thunkFunctionType=InternalFunction, kind=<unavailable>, entryType=EnterViaCall) at ThunkGenerators.cpp:496:16 [opt]
    frame #6: 0x00000001013c3da4 jsc`JSC::internalFunctionCallGenerator(vm=<unavailable>) at ThunkGenerators.cpp:522:12 [opt] [artificial]
    frame #7: 0x000000010139e9b0 jsc`JSC::JITThunks::ctiStub(JSC::VM&, JSC::MacroAssemblerCodeRef<(WTF::PtrTag)26129> (*)(JSC::VM&)) [inlined] JSC::JITThunks::ctiStub(this=<unavailable>)26129> (*)(JSC::VM&))::$_2::operator()() const at JITThunks.cpp:170:16 [opt]
    frame #8: 0x000000010139e9a4 jsc`JSC::JITThunks::ctiStub(JSC::VM&, JSC::MacroAssemblerCodeRef<(WTF::PtrTag)26129> (*)(JSC::VM&)) [inlined] JSC::MacroAssemblerCodeRef<(WTF::PtrTag)26129> JSC::JITThunks::ctiStubImpl<JSC::JITThunks::ctiStub(this=0x00000001052a42d0, key=(jsc`JSC::internalFunctionCallGenerator(JSC::VM&) at ThunkGenerators.cpp:521), generateThunk=<unavailable>)26129> (*)(JSC::VM&))::$_2>(JSC::MacroAssemblerCodeRef<(WTF::PtrTag)26129> (*)(JSC::VM&), JSC::JITThunks::ctiStub(JSC::VM&, JSC::MacroAssemblerCodeRef<(WTF::PtrTag)26129> (*)(JSC::VM&))::$_2) at JITThunks.cpp:159:53 [opt]
    frame #9: 0x000000010139e7fc jsc`JSC::JITThunks::ctiStub(this=0x00000001052a42d0, vm=0x0000000105600000, generator=(jsc`JSC::internalFunctionCallGenerator(JSC::VM&) at ThunkGenerators.cpp:521))26129> (*)(JSC::VM&)) at JITThunks.cpp:169:12 [opt]
    frame #10: 0x000000010139f2d8 jsc`JSC::JITThunks::ctiInternalFunctionCall(this=0x00000001052a42d0, vm=0x0000000105600000) at JITThunks.cpp:123:12 [opt]
    frame #11: 0x0000000101ba8b48 jsc`JSC::VM::VM(this=0x0000000105600000, vmType=<unavailable>, heapType=<unavailable>, runLoop=<unavailable>, success=0x0000000000000000) at VM.cpp:397:9 [opt]
    frame #12: 0x0000000101bacfc4 jsc`JSC::VM::create(JSC::HeapType, WTF::RunLoop*) [inlined] JSC::VM::VM(this=<unavailable>, vmType=Default, heapType=LargeHeap, runLoop=0x0000000000000000, success=0x0000000000000000) at VM.cpp:242:1 [opt]
    frame #13: 0x0000000101bacfb0 jsc`JSC::VM::create(heapType=<unavailable>, runLoop=<unavailable>) at VM.cpp:523:26 [opt]
    frame #14: 0x000000010000bd18 jsc`jscmain(int, char**) [inlined] int runJSC<jscmain(int, char**)::$_6>(options=<unavailable>, isWorker=false, func=<unavailable>)::$_6 const&) at jsc.cpp:3763:14 [opt]
    frame #15: 0x000000010000bca0 jsc`jscmain(argc=1, argv=<unavailable>) at jsc.cpp:3997:18 [opt]
    frame #16: 0x000000010000b80c jsc`main(argc=<unavailable>, argv=<unavailable>) at jsc.cpp:3162:15 [opt]
    frame #17: 0x00000001039e50f4 dyld`start + 520
(lldb) 

```

**Comment by saelo** [comment]
Hmm I vaguely seem to remember issues on the M1 with JSC built with cmake...  can you try manually enabling (i.e., define to `1`) `USE_PTHREAD_JIT_PERMISSIONS_API` in `FuzzBuild/Debug/WTF/Headers/wtf/PlatformUse.h` and recompile with that?

**Comment by fr3ns1s** [comment]
bingo! thanks

```
➜  fuzzilli git:(main) ✗ swift run -c release FuzzilliCli --profile=jsc --storagePath=Crash --overwrite --jobs=48 /Users/fp/Documents/Git/WebKitFuzzilli/FuzzBuild/Debug/bin/jsc
[0/0] Build complete!
[Cli] Deleting all files in Crash due to --overwrite
[Coverage] Initialized, 924600 edges
[JavaScriptEnvironment] initialized static JS environment model
[JavaScriptEnvironment] Have 60 available builtins: ["Array", "RegExp", "Proxy", "Infinity", "Uint8ClampedArray", "SyntaxError", "Uint8Array", "transferArrayBuffer", "EvalError", "Map", "parseInt", "placeholder", "createGlobalObject", "runString", "fiatInt52", "DataView", "Error", "AggregateError", "Set", "noInline", "Function", "String", "Int16Array", "eval", "Int8Array", "WeakMap", "JSON", "parseFloat", "Promise", "RangeError", "Float32Array", "ReferenceError", "noFTL", "Int32Array", "Symbol", "WeakSet", "Object", "OSRExit", "drainMicrotasks", "Uint16Array", "edenGC", "undefined", "Boolean", "isFinite", "ArrayBuffer", "gc", "Reflect", "NaN", "Float64Array", "Uint32Array", "TypeError", "fullGC", "forceGCSlowPaths", "makeMasquerader", "Date", "isNaN", "Number", "ensureArrayStorage", "Math", "BigInt"]
[JavaScriptEnvironment] Have 211 available method names: ["getHours", "set", "floor", "charAt", "codePointAt", "setUint32", "push", "o", "asin", "toLowerCase", "log10", "fromCodePoint", "getUint16", "min", "getOwnPropertyNames", "asIntN", "repeat", "round", "unshift", "forEach", "setUTCDate", "toISOString", "concat", "setPrototypeOf", "create", "add", "asinh", "call", "from", "abs", "getUint8", "setSeconds", "tan", "toGMTString", "trimLeft", "setTime", "getOwnPropertyDescriptors", "resolve", "sqrt", "slice", "assign", "imul", "clear", "UTC", "fill", "every", "parse", "charCodeAt", "trim", "indexOf", "expm1", "map", "getMonth", "tanh", "get", "pop", "getUTCDay", "atan2", "fromEntries", "splice", "cosh", "getTimezoneOffset", "isSealed", "getUTCDate", "setMinutes", "atanh", "toTimeString", "isNaN", "race", "sinh", "getUint32", "hypot", "padEnd", "find", "allSettled", "filter", "setUTCSeconds", "matchAll", "then", "setInt32", "getYear", "localeCompare", "setFullYear", "test", "construct", "freeze", "acosh", "max", "setUTCFullYear", "stringify", "isView", "getUTCSeconds", "getUTCMilliseconds", "clz32", "exec", "isFinite", "getInt8", "defineProperty", "cbrt", "reduce", "match", "getPrototypeOf", "getUTCMinutes", "setFloat64", "lastIndexOf", "startsWith", "setFloat32", "toDateString", "log2", "toLocaleString", "delete", "replaceAll", "includes", "setYear", "sort", "setMonth", "ceil", "isExtensible", "preventExtensions", "for", "fround", "keyFor", "getUTCHours", "toJSON", "asUintN", "subarray", "n", "setInt8", "setUint8", "apply", "shift", "isInteger", "of", "now", "join", "atan", "toUpperCase", "getSeconds", "catch", "isArray", "getDate", "reverse", "setMilliseconds", "isFrozen", "setUTCMinutes", "ownKeys", "getTime", "trimRight", "m", "setDate", "getInt16", "seal", "trimStart", "padStart", "bind", "getInt32", "setInt16", "entries", "cos", "toString", "setHours", "split", "defineProperties", "sign", "reject", "substring", "toUTCString", "getOwnPropertyDescriptor", "findIndex", "some", "values", "getDay", "getMilliseconds", "sin", "isSafeInteger", "replace", "getUTCFullYear", "trunc", "flat", "log1p", "exp", "all", "setUint16", "getUTCMonth", "deleteProperty", "log", "p", "copyWithin", "setUTCMonth", "setUTCMilliseconds", "reduceRight", "fromCharCode", "getFloat64", "is", "finally", "pow", "getFullYear", "getMinutes", "compile", "search", "trimEnd", "raw", "getFloat32", "keys", "random", "acos", "flatMap", "getOwnPropertySymbols", "setUTCHours", "endsWith", "has"]
[JavaScriptEnvironment] Have 51 property names that are available for read access: ["buffer", "MAX_SAFE_INTEGER", "species", "byteOffset", "NEGATIVE_INFINITY", "size", "arguments", "match", "MIN_SAFE_INTEGER", "d", "search", "length", "replace", "iterator", "MAX_VALUE", "__proto__", "EPSILON", "name", "asyncIterator", "split", "sticky", "PI", "multiline", "matchAll", "ignoreCase", "unscopable", "flags", "toString", "constructor", "isConcatSpreadable", "toPrimitive", "global", "a", "b", "dotAll", "toStringTag", "E", "POSITIVE_INFINITY", "prototype", "description", "byteLength", "unicode", "NaN", "e", "MIN_VALUE", "hasInstance", "source", "message", "c", "valueOf", "caller"]
[JavaScriptEnvironment] Have 10 property names that are available for write access: ["c", "constructor", "toString", "a", "valueOf", "e", "__proto__", "b", "d", "length"]
[JavaScriptEnvironment] Have 5 custom property names: ["c", "e", "d", "b", "a"]
[JavaScriptEnvironment] Have 4 custom method names: ["m", "n", "o", "p"]
[Fuzzer] Initialized
[Fuzzer] Recommended timeout: at least 100ms. Current timeout: 250ms
[Fuzzer] Startup tests finished successfully
[DC59F831:Fuzzer] Initialized
[4A01BF58:Fuzzer] Initialized
```

**Comment by turnerrocks1** [comment]
@fr3ns1s did you define it to 1 or 0 to get it working ?

**Comment by fr3ns1s** [comment]
> @fr3ns1s did you define it to 1 or 0 to get it working ?

1

**Comment by turnerrocks1** [comment]
@fr3ns1s o yea i had figured it out thank you
