### ISSUE TITLE
ReferenceError: fuzzilli is not defined And TypeError: Object template has duplicate property 'undefined'

### ISSUE THREAD

**Issue by Vincebye** [googleprojectzero/fuzzilli#385]
When I used fuzzilli to fuzz v8, there were a lot of crashes, but when I tested these crashes, I found that they were based on two kinds of errors, one is
`C:\Users\vince\Downloads\sto\sto\crashes\program_20221130235710_658D5DF0-EBC6-4E13-9442-8804B9A2BDFE_flaky.js:127: ReferenceError: fuzzilli is not defined
        fuzzilli('FUZZILLI_PRINT', 'EXPLORE_ERROR: ' + msg);
        ^
ReferenceError: fuzzilli is not defined
    at reportError (C:\Users\vince\Downloads\sto\sto\crashes\program_20221130235710_658D5DF0-EBC6-4E13-9442-8804B9A2BDFE_flaky.js:127:9)
    at exploreWithErrorHandling (C:\Users\vince\Downloads\sto\sto\crashes\program_20221130235710_658D5DF0-EBC6-4E13-9442-8804B9A2BDFE_flaky.js:762:17)
    at v0 (C:\Users\vince\Downloads\sto\sto\crashes\program_20221130235710_658D5DF0-EBC6-4E13-9442-8804B9A2BDFE_flaky.js:770:5)
    at main (C:\Users\vince\Downloads\sto\sto\crashes\program_20221130235710_658D5DF0-EBC6-4E13-9442-8804B9A2BDFE_flaky.js:782:17)
    at C:\Users\vince\Downloads\sto\sto\crashes\program_20221130235710_658D5DF0-EBC6-4E13-9442-8804B9A2BDFE_flaky.js:820:1
`
The other is
`C:\Users\vince\Downloads\sto\sto\crashes\duplicates\program_20221204065011_EE59CDA0-D229-431F-BFDF-00A08DDD682B_deterministic.js:4: TypeError: Object template has duplicate property 'undefined'
const v5 = v4(Int16Array);
            ^
TypeError: Object template has duplicate property 'undefined'
     at SharedStructType (<anonymous>)
     at main (C:\Users\vince\Downloads\sto\sto\crashes\duplicates\program_20221204065011_EE59CDA0-D229-431F-BFDF-00A08DDD682B_deterministic.js:4:12)
     at C:\Users\vince\Downloads\sto\sto\crashes\duplicates\program_20221204065011_EE59CDA0-D229-431F-BFDF-00A08DDD682B_deterministic.js:8:1`
Is this normal? How can I avoid this false positive?
`The format of the crash sample command I executed is E:\\fuzzing\\browser\\chrome\\asan-win32-release_x64-1070968\\d8.exe --expose-gc --future --harmony --assert-types - -harmony-rab-gsab --harmony-struct --allow-natives-syntax --interrupt-budget=1000 --fuzzing xxxxxxxxxxxx/xxxx.js`

**Comment by saelo** [comment]
They are probably crashes from the ExplorationMutator or ProbingMutator. You could try adding `function fuzzilli() {}` to the start of the samples. If this happens frequently, feel free to send a PR to e.g. make sure the `fuzzilli` function exists here: https://github.com/googleprojectzero/fuzzilli/blob/f7dfd455969c24a31af182fafde889c0ff68ebac/Sources/Fuzzilli/Lifting/JavaScriptExploreLifting.swift#L167 (and in JavaScriptProbeLifting.swift)

**Comment by saelo** [comment]
Closing this now, but let me know if there are any further issues here
