### ISSUE TITLE
Assertion failed: Expected variable declaration as init part of a for-in loop, found Identifier

### ISSUE THREAD

**Issue by nth10sd** [googleprojectzero/fuzzilli#412]
node parser.js ../../Protobuf/ast.proto code.js output.ast.proto

`code.js`:

```
for (x in y) {}
```

Tested on rev d386a838.

```
<repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:17
            throw "Assertion failed: " + msg;
            ^
Assertion failed: Expected variable declaration as init part of a for-in loop, found Identifier
Thrown at:
    at assert (<repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:17:13)
    at visitStatement (<repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:268:17)
    at visitProgram (<repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:51:37)
    at parse (<repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:561:12)
    at <repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:570:15
    at finish (<repo>/Sources/Fuzzilli/Compiler/Parser/node_modules/protobufjs/src/root.js:105:9)
    at process (<repo>/Sources/Fuzzilli/Compiler/Parser/node_modules/protobufjs/src/root.js:143:13)
    at <repo>/Sources/Fuzzilli/Compiler/Parser/node_modules/protobufjs/src/root.js:195:17
    at fetchReadFileCallback (<repo>/Sources/Fuzzilli/Compiler/Parser/node_modules/@protobufjs/fetch/index.js:51:19)
    at readFileAfterClose (node:internal/fs/read/context:68:3)
```

**Comment by saelo** [comment]
Ah good catch, I think this is actually a problem with the IL rather than the compiler/parser as we currently expect [ForIn loops to define a new variable](https://github.com/googleprojectzero/fuzzilli/blob/d386a83812496b7e590ce93c8fdc50208dacbd26/Sources/Fuzzilli/FuzzIL/JsOperations.swift#L1971) (they must have one inner output), while in this case we'd either reuse an existing variable or create a global one. So I think fixing this properly might require introducing a new IL operation like `ForInWithReassign`.
