### ISSUE TITLE
Unknown property key type: StringLiteral

### ISSUE THREAD

**Issue by nth10sd** [googleprojectzero/fuzzilli#416]
node parser.js ../../Protobuf/ast.proto code.js output.ast.proto

`code.js`:

```
x = { "": 0 }
```

Tested on rev d42d6fa0a.

```
<repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:393
                                throw "Unknown property key type: " + field.key.type;
                                ^
Unknown property key type: StringLiteral
Thrown at:
    at visitExpression (<repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:393:33)
    at visitExpression (<repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:375:27)
    at visitStatement (<repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:119:28)
    at visitProgram (<repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:51:37)
    at parse (<repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:561:12)
    at <repo>/Sources/Fuzzilli/Compiler/Parser/parser.js:570:15
    at finish (<repo>/Sources/Fuzzilli/Compiler/Parser/node_modules/protobufjs/src/root.js:105:9)
    at process (<repo>/Sources/Fuzzilli/Compiler/Parser/node_modules/protobufjs/src/root.js:143:13)
    at <repo>/Sources/Fuzzilli/Compiler/Parser/node_modules/protobufjs/src/root.js:195:17
    at fetchReadFileCallback (<repo>/Sources/Fuzzilli/Compiler/Parser/node_modules/@protobufjs/fetch/index.js:51:19)
```

**Comment by areuu** [comment]
This best to improve code by yourself.

**Comment by b4sh5i** [comment]
any one fix this problem? i want to fix that.
