### ISSUE TITLE
compile gecko error

### ISSUE THREAD

**Issue by rain6851** [googleprojectzero/fuzzilli#52]
mozbuild.configure.options.InvalidOptionError: --disable-shared-js is not available in this configuration
make: *** No targets specified and no makefile found.  Stop.

**Comment by rain6851** [comment]
@saelo

**Comment by rain6851** [comment]
After remove --disable-shared-js

There will still have error:
```
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/config/recurse.mk:32: recipe for target 'compile' failed
make[1]: *** [compile] Error 2
make[1]: Leaving directory '/root/fuzzilli/Targets/Spidermonkey/gecko-dev/fuzzbuild_OPT.OBJ'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/config/rules.mk:391: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by rain6851** [comment]
```
prpolevt.o: In function `PR_NewPollableEvent':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prpolevt.c:160: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prpolevt.c:126: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prpolevt.c:131: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prpolevt.c:116: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prpolevt.c:136: undefined reference to `__sanitizer_cov_trace_pc_guard'
prpolevt.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prpolevt.c:171: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
prpolevt.o: In function `sancov.module_ctor':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prpolevt.c:(.text.sancov.module_ctor+0x10): undefined reference to `__sanitizer_cov_trace_pc_guard_init'
linux.o: In function `_MD_EarlyInit':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/md/unix/linux.c:9: undefined reference to `__sanitizer_cov_trace_pc_guard'
linux.o: In function `_MD_HomeGCRegisters':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/md/unix/linux.c:13: undefined reference to `__sanitizer_cov_trace_pc_guard'
linux.o: In function `sancov.module_ctor':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/md/unix/linux.c:(.text.sancov.module_ctor+0x10): undefined reference to `__sanitizer_cov_trace_pc_guard_init'
praton.o: In function `pr_inet_aton':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/praton.c:118: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/praton.c:118: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/praton.c:123: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/praton.c:123: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/praton.c:137: undefined reference to `__sanitizer_cov_trace_pc_guard'
praton.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/praton.c:123: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
praton.o: In function `sancov.module_ctor':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/praton.c:(.text.sancov.module_ctor+0x10): undefined reference to `__sanitizer_cov_trace_pc_guard_init'
prcountr.o: In function `PR_CreateCounter':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prcountr.c:126: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prcountr.c:130: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prcountr.c:131: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prcountr.c:132: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prcountr.c:148: undefined reference to `__sanitizer_cov_trace_pc_guard'
prcountr.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prcountr.c:121: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
prcountr.o: In function `sancov.module_ctor':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prcountr.c:(.text.sancov.module_ctor+0x10): undefined reference to `__sanitizer_cov_trace_pc_guard_init'
Unified_c_external_nspr_pr0.o: In function `_PR_Getfd':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prfdcach.c:81: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prfdcach.c:75: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prfdcach.c:88: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prfdcach.c:66: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prfdcach.c:86: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prfdcach.c:87: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
Unified_c_external_nspr_pr0.o: In function `_PR_InitLinker':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:169: undefined reference to `dlopen'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:140: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:147: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:197: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:203: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:203: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o: In function `DLLErrorInternal':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:127: undefined reference to `dlerror'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:124: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:136: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:135: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o: In function `_PR_ShutdownLinker':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:218: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:225: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:224: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
Unified_c_external_nspr_pr0.o: In function `pr_LoadLibraryByPathname':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:803: undefined reference to `dlopen'
Unified_c_external_nspr_pr0.o: In function `PR_LoadLibraryWithFlags':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:412: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:430: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o: In function `pr_LoadLibraryByPathname':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:657: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:696: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:831: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:936: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
Unified_c_external_nspr_pr0.o: In function `PR_UnloadLibrary':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:992: undefined reference to `dlclose'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1028: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1040: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:963: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:976: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1024: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:958: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
Unified_c_external_nspr_pr0.o: In function `pr_FindSymbolInLib':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1161: undefined reference to `dlsym'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1178: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1076: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1068: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1078: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1086: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1179: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
Unified_c_external_nspr_pr0.o: In function `PR_GetLibraryFilePathname':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1341: undefined reference to `dladdr'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1336: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1348: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1342: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/linking/prlink.c:1347: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o: In function `_PR_DestroyZones':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/malloc/prmem.c:64: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/malloc/prmem.c:65: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
Unified_c_external_nspr_pr0.o: In function `pr_FindSymbolInProg':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/malloc/prmem.c:98: undefined reference to `dlopen'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/malloc/prmem.c:101: undefined reference to `dlsym'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/malloc/prmem.c:102: undefined reference to `dlclose'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/malloc/prmem.c:99: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o: In function `_PR_InitZones':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/malloc/prmem.c:163: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/malloc/prmem.c:164: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/malloc/prmem.c:179: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/malloc/prmem.c:149: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr0.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/malloc/prmem.c:167: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
Unified_c_external_nspr_pr0.o: In function `sancov.module_ctor':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/io/prscanf.c:(.text.sancov.module_ctor+0x10): undefined reference to `__sanitizer_cov_trace_pc_guard_init'
Unified_c_external_nspr_pr1.o: In function `_MD_unix_map_default_error':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/md/unix/unix_errors.c:13: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/md/unix/unix_errors.c:16: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/md/unix/unix_errors.c:16: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr1.o: In function `PR_SetError':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prerror.c:24: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr1.o: In function `_MD_unix_map_opendir_error':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/md/unix/unix_errors.c:234: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr1.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/md/unix/unix_errors.c:16: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
Unified_c_external_nspr_pr1.o: In function `sancov.module_ctor':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prdtoa.c:(.text.sancov.module_ctor+0x10): undefined reference to `__sanitizer_cov_trace_pc_guard_init'
Unified_c_external_nspr_pr2.o: In function `PR_TicksPerSecond':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prinrval.c:43: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr2.o: In function `_PR_InitClock':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prinrval.c:23: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prinrval.c:29: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr2.o: In function `PR_TicksPerSecond':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prinrval.c:43: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr2.o: In function `_PR_InitClock':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prinrval.c:30: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr2.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/misc/prinrval.c:30: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
Unified_c_external_nspr_pr2.o: In function `PR_SetCurrentThreadName':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/pthreads/ptthread.c:1650: undefined reference to `dlsym'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/pthreads/ptthread.c:1624: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/pthreads/ptthread.c:1630: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/pthreads/ptthread.c:1651: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/pthreads/ptthread.c:1682: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/pthreads/ptthread.c:1613: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr2.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/pthreads/ptthread.c:1619: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
Unified_c_external_nspr_pr2.o: In function `sancov.module_ctor':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/pthreads/ptthread.c:(.text.sancov.module_ctor+0x10): undefined reference to `__sanitizer_cov_trace_pc_guard_init'
Unified_c_external_nspr_pr3.o: In function `_PR_InitCMon':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/threads/prcmon.c:297: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr3.o: In function `ExpandMonitorCache':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/threads/prcmon.c:111: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/threads/prcmon.c:113: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/threads/prcmon.c:105: undefined reference to `__sanitizer_cov_trace_pc_guard'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/threads/prcmon.c:111: undefined reference to `__sanitizer_cov_trace_pc_guard'
Unified_c_external_nspr_pr3.o:/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/threads/prcmon.c:117: more undefined references to `__sanitizer_cov_trace_pc_guard' follow
Unified_c_external_nspr_pr3.o: In function `sancov.module_ctor':
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/nsprpub/pr/src/threads/prtpd.c:(.text.sancov.module_ctor+0x10): undefined reference to `__sanitizer_cov_trace_pc_guard_init'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/config/rules.mk:658: recipe for target 'libnspr4.so' failed
make[3]: *** [libnspr4.so] Error 1
make[3]: Leaving directory '/root/fuzzilli/Targets/Spidermonkey/gecko-dev/fuzzbuild_OPT.OBJ/config/external/nspr/pr'
/root/fuzzilli/Targets/Spidermonkey/gecko-dev/config/recurse.mk:74: recipe for target 'config/external/nspr/pr/target' failed
make[2]: *** [config/external/nspr/pr/target] Error 2
```

**Comment by saelo** [comment]
This should be fixed now with https://github.com/googleprojectzero/fuzzilli/commit/c60c2e60a0ba62bb27d8d0d04fc8cb98774b1945 please reopen this issue or file a new one if it still doesn't work :)

**Comment by 0xShad3** [comment]
Hello there!

After trying to compile the latest version of gecko/Spidermonkey, I apparently get back that --enable-js-fuzzilli is not supported (anymore?) 
```
Using Python 3.6.9 from /usr/bin/python3
created virtual environment CPython3.6.9.final.0-64 in 33ms
  creator CPython3Posix(dest=/home/v8pwn/Desktop/spidermonkey/gecko-dev/fuzzbuild_OPT.OBJ/_virtualenvs/build, clear=False, no_vcs_ignore=False, global=False)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator
Created Python 3 virtualenv
checking for vcs source checkout... git
checking for a shell... /bin/sh
checking for host system type... x86_64-pc-linux-gnu
checking for target system type... x86_64-pc-linux-gnu
checking whether cross compiling... no
Traceback (most recent call last):
  File "../configure.py", line 349, in <module>
    sys.exit(main(sys.argv))
  File "../configure.py", line 131, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), "moz.configure"))
  File "/home/v8pwn/Desktop/spidermonkey/gecko-dev/python/mozbuild/mozbuild/configure/__init__.py", line 516, in run
    self._value_for(option)
  File "/home/v8pwn/Desktop/spidermonkey/gecko-dev/python/mozbuild/mozbuild/configure/__init__.py", line 621, in _value_for
    return self._value_for_option(obj)
  File "/home/v8pwn/Desktop/spidermonkey/gecko-dev/python/mozbuild/mozbuild/util.py", line 1061, in method_call
    cache[args] = self.func(instance, *args)
  File "/home/v8pwn/Desktop/spidermonkey/gecko-dev/python/mozbuild/mozbuild/configure/__init__.py", line 690, in _value_for_option
    % option_string.split("=", 1)[0]
mozbuild.configure.options.InvalidOptionError: --enable-js-fuzzilli
``` 
Thanks for your time !

**Comment by 0xShad3** [comment]
@saelo  @drtychai @amarekano
